### ISSUE TITLE
Incorrect Package Name in README.md

### ISSUE THREAD

**Issue by 0x3c** [10k-swap/10k_swap-sdk#1]
The name field in the package.json file is set to `l0k_swap-sdk`. Therefore, to utilize this SDK, the package should be imported using the name `l0k_swap-sdk`.

 However, all references to the package name in the `README.md` file are listed as `10k_swap-sdk`. This inconsistency is causing issues, should align the package name for clarity and consistency?

**Comment by breeze98** [comment]
Thanks for your feedback, we have changed the name of the example
